### ISSUE TITLE
not repeat 

### ISSUE THREAD

**Issue by amirtaherkhani** [rommelsantor/Timeout#14]
Timeout  called  my callback only once !! 
Timeout.set("cpu_info", getInformation, millisecs = 9000, ["cache", "voltage", "flags"]);

**Comment by rommelsantor** [comment]
Hi @amirtaherkhani. That is the expected behavior.

`Timeout.set()` is equivalent to `setTimeout()`, which is also executed only once, and not equivalent to `setInterval()` which executes repeatedly.

A simple solution is to make the `Timeout.set()` call part of the callback.
