### ISSUE TITLE
Cannot import Timeout through HTML. [ReferenceError: exports is not defined]

### ISSUE THREAD

**Issue by abanoy** [rommelsantor/Timeout#16]
Hello,

I tried using this HTML to import the code:
<script crossorigin="anonymous" src="https://cdn.jsdelivr.net/npm/smart-timeout@2.6.1/index.js">var exports = {};</script>

But it gives me a ReferenceError as the title says above. From what I read, I believe I need to have CommonJS library imported.

I want to use this library for my repository that is hosted on GitHub Pages. Can you help me?

**Comment by rommelsantor** [comment]
@abanoy Please give this a try:

    <script>var exports = {}</script>
    <script src="https://cdn.jsdelivr.net/npm/smart-timeout@2.6.1/lib/timeout.js"></script>

Then you should be able to freely use `Timeout`.

    <script>
      Timeout.set(() => console.log('foo'), 1000)
    </script>

That should solve it for you, so I'll close this, but let me know if not!
