### ISSUE TITLE
give instantiate an optional key as well

### ISSUE THREAD

**Issue by emahuni** [rommelsantor/Timeout#17]
I know in the documentation it says that this "defeats the purpose of instantiate", however, the good thing about this lib is that `key` feature which makes it easier to keep track of all timeouts from anywhere. I think this option will make it possible to the following: 

```js
let t = timeout.instantiate('huga', ()=>console.log('blah'), 3000);
// ... do things with t
// this should still work as usual, but we can't get this from anywhere else since there is no key
let toto = timeout.instantiate(()=>console.log('blah'), 3000);
```

somewhere else where there is no access to `t`

```js
console.log('t remaining time: ', timeout.remaining('huga'));
// or get and use the instance here
let tt = timeout('huga');
tt.restart()
```

**Comment by rommelsantor** [comment]
Can you explain the scenario in which this would be necessary?

I'm unsure how useful this feature would be in practice.

**Comment by emahuni** [comment]
I'm using this in Vue and components have isolated states. However there's a need to use the same instance without passing around the actual instance within across components. The reason why I like this lib is coz it keeps track of it's own timers, and accessing one is just a matter of knowing its key. This is very important in situations where state isolation is being done coz you want to restart the timer or check remaining only when it's there, and not pass around a handling var in global state...

**Comment by rommelsantor** [comment]
@emahuni Added in v2.7.0. Thanks!
