### ISSUE TITLE
reset or renew a timeout

### ISSUE THREAD

**Issue by emahuni** [rommelsantor/Timeout#18]
This enables rekindling a dead timeout as if it's new
```js
timeout.set('huga', ()=>console.log('huga done!'), 5000);
// ... later on after the whole thing is dead, maybe after 12000ms
timeout.renew('huga')
// if this was instantiated to t...
t.renew()
```
That will just reinstantiate the timeout and replace it in mem. 

optionally we could set new delay

```js
timeout.renew('huga', 400)
// if this was instantiated to t...
t.renew(400)
```

**Comment by emahuni** [comment]
Notice this is like what `set` does, but without another callback, and it doesn't replace any instances, it should just modify it.

**Comment by rommelsantor** [comment]
This makes sense to me. We do have a `restart()` that will restart for a timeout that has not yet executed, but there is no way to `reset()` a timeout that has already executed.

I'd probably just call it `reset()` rather than `renew()`.

**Comment by rommelsantor** [comment]
@emahuni Added in v2.7.0. Thanks!
