### ISSUE TITLE
instance information via .info

### ISSUE THREAD

**Issue by emahuni** [rommelsantor/Timeout#19]
There is currently no way of getting information about the instance

```js
timeout.set('huga', ()=>console.log('huga done!'), 5000);
// ... later we may want to know info about this timeout
timeout.info('huga')
// returns something like => { name: 'huga', cb ƒ, delay: 5000}
// if this was instantiated to t...
t.info()
```

**Comment by rommelsantor** [comment]
What is the use case for this?

Is this something you've actually found yourself in need of?

**Comment by emahuni** [comment]
Yes. If you read what I have been writing as use cases. Sometimes we don't have access or don't want to bloat code with vars trying to keep track of something that is keeping track for us, ie, we need to know the initial timeout info used so we can calculate other info or display other info EG: calculate elapsed time based on remaining...  or just display the remaining of total.

**Comment by rommelsantor** [comment]
@emahuni Added in v2.7.0. Thanks!
