### ISSUE TITLE
Install via npm/yarn

### ISSUE THREAD

**Issue by jrhorn424** [rommelsantor/Timeout#2]
Would you accept a PR that publishes this to npm for easy installation? I could convert this to esnext modules, or I could add that as an option. The latter is more work. 😛

**Comment by rommelsantor** [comment]
Thanks for the suggestion, @jrhorn424! I'd considered it in passing previously, but now that you've spurred me on, I've gone ahead and published into npm: https://www.npmjs.com/package/smart-timeout 😁

**Comment by jrhorn424** [comment]
Awesome, thanks @rommelsantor!
