### ISSUE TITLE
Add ability to invoke timed out function immediately

### ISSUE THREAD

**Issue by cvaccarello** [rommelsantor/Timeout#6]
So I'm a little new at this, not sure what to expect, but it would be cool if there was a public method for invoking (and optionally clearing immediately?) the timeout.  Obviously the function can be stored some where and later triggered manually & then the timeout cleared, but poking around in the code shows an invoke method of sorts already exists, it's just not public.

Something like this maybe? 🤷‍♂ 
```js
  const invoke = key => {
    if (!pending(key)) { return; }
    metadata[key].func(...metadata[key].params)
    clear(key)
  }
```

**Comment by rommelsantor** [comment]
Hi, Chris. It sounds like you mean that you would set a timeout then decide instead to execute the function prematurely and optionally clear the timeout. Can you provide a use case where this functionality would be valuable? Thanks!

**Comment by cvaccarello** [comment]
Yup that's what I mean; maybe an example would be scheduling a form to auto save in 10 minutes, but then the user presses save and you want to jump ahead and do it now.

I'm trying to figure out a better example than the scenario I have right now 😅 b/c the scenario now is that I'm waiting for a CSS animation to finish, however when the user swipes I want to quickly call the callback now, rather than waiting.

Does that help?  I admit, it's not a super strong reason for having it, you could easily store the function you're going to call (like a save, or something when an animation finishes) in a variable and then just invoke it manually, but maybe in scenarios where the function only exists in that timeout, being able to trigger it would be useful?

**Comment by rommelsantor** [comment]
Thanks for the reply!

I think it's a rare edge case and not a valuable use of Timeout as a function courier. If you really did want to use Timeout for this type of short-circuiting, you could just call `Timeout.set()` again with `millisecs` set to 0.

**Comment by cvaccarello** [comment]
Yeah I thought about the set time with 0 milliseconds, the problem was I still needed the function to be stored in a variable or something, and again, at that point I can just do it myself.

I guess I look at it like... you could store every callback function in a variable, always doing something like
```
var foo = () => {
   // my code
}

someMethod(foo);
```

OR, a more compact approach

```
someMethod(() => {
   // my code
});
```

So I was just thinking that instead of forcing every function to be stored in a variable, since it's already stored as part of the timeout, why not let us call / trigger the timeout.

Anyways, thanks for your time!  I can probably just make a wrapper to store the function before using the Timeout code.
