### ISSUE TITLE
use function toString as key is not safe 

### ISSUE THREAD

**Issue by ash0080** [rommelsantor/Timeout#7]
as title

**Comment by rommelsantor** [comment]
Hi @ash0080. Can you please elaborate on your thoughts? Thanks!

**Comment by ash0080** [comment]
For example call timeout in a factory loop func,  the functions to string is always same, consider use an internal counter or use new Map() replace the Object structure.  cuz Map could accept func or object as key, weak map better

**Comment by rommelsantor** [comment]
I wouldn't call the possibility of unintentional key collisions "not safe."

I'd also say caveat emptor. If you use the function as your unique key but you aren't passing a unique function, that is the functionality that is advertised.

It's up to the consumer to define a unique key if they want identical functions to be treated as unique, not the job of the library to guess whether or not the consumer intended to reference a different key using the same function definition.

Thanks for sharing your thoughts!
