### ISSUE TITLE
Ability to reference a specific timeout and calls functions on it

### ISSUE THREAD

**Issue by alechirsch** [rommelsantor/Timeout#8]
This package looks really good in terms of functionality. One area I see for improvement is the ability to reference a timeout itself as a variable and call all available functions on the timeout.
Having that ability will allow to create timers and pass them to different areas of my code that might want to know about it. Currently it is difficult to get status on a timeout if it was created in one file and then passed into another.

Here is an example of what I would like to see
```
const Timeout = require('smart-timeout');

let newTimeout = Timeout(function(){ return 'does stuff'}, 1000);
newTimeout.remaining();
newTimeout.executed();
etc...
```

Do you have additional thoughts on this?

**Comment by rommelsantor** [comment]
Hi, @alechirsch,

While my initial approach intended to make it function much like the `setTimeout()` and `clearTimeout()` natives, you make a solid point and this would help make it a more powerful utility.

As soon as I have a minute, I'm going to look into supporting something like this. Stay tuned!

Thanks for the suggestion!

**Comment by alechirsch** [comment]
@rommelsantor Thanks for the work on this, looks good
