### ISSUE TITLE
switching to Typescript?

### ISSUE THREAD

**Issue by MarcusCalidus** [rommelsantor/Timeout#9]
Hi @rommelsantor ,

I know this could be a controversial topic. 

What do you think about switching this library to Typescript? 

I am using your library in several larger inhouse projects. For that I have had to expand some functionality. I would love to do it by overriding. But that's not so safe if there is no possibility for type checking in place (in case the backend changes). Therefore I had to fork your project https://github.com/MarcusCalidus/Timeout.git

If you are into the idea of moving to Typescript I'd gladly offer my help for translating the library.

**Comment by rommelsantor** [comment]
Hi @MarcusCalidus!

I appreciate the suggestion and offer to assist. I'd be happy to look at a PR for your translation to TypeScript.

Thanks!

**Comment by MarcusCalidus** [comment]
This topic is addressed in PR10 https://github.com/rommelsantor/Timeout/pull/10
